### ISSUE TITLE
Document Api

### ISSUE THREAD

**Issue by cooper-roper** [climate-cooperative/home-energy-assessment-database#35] opened 2024-04-29 23:28 UTC
## Description

Add technical document to describe the API routes

## Technical Notes

Routes are

/state
/zipcode
/appliances
/hvac
/home_type
/home_decade

## Risks

[]

**Comment by rgraue** [comment] 2024-05-22 17:53
Duplicate of #31

**Closed by rgraue** 2024-05-22 17:53 UTC
